# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('area', models.IntegerField()),
                ('households', models.IntegerField()),
                ('volume_rage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('greening_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
