# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fspider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='volume_rage',
            new_name='volume_rate',
        ),
    ]
