# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fspider', '0002_auto_20161217_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='href',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='greening_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='house',
            name='households',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='volume_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
