# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fspider', '0003_auto_20161217_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='N/A', max_length=100)),
                ('category', models.CharField(default='N/A', max_length=100)),
                ('area', models.IntegerField(default=0)),
                ('parking', models.CharField(default='N/A', max_length=100)),
                ('href', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='N/A', max_length=100)),
                ('category', models.CharField(default='N/A', max_length=100)),
                ('area', models.IntegerField(default=0)),
                ('parking', models.CharField(default='N/A', max_length=100)),
                ('href', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='N/A', max_length=100)),
                ('area', models.IntegerField(default=0)),
                ('households', models.IntegerField(default=0)),
                ('volume_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('greening_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('href', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
