# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-18 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fspider', '0004_office_shop_villa'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='hx_position',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='region',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='villa',
            name='hx_position',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='villa',
            name='region',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
